export const booksArr = [
  {
    _id: "64060df6885aa09e184268dd",
    author: "Автор1",
    deadline: "2023-03-30",
    friendsbook: true,
    name: "Имя друга 1",
    notes: ["Заметка к книге Гарри Поттер"],
    patronymic: "Отчество друга 1",
    surname: "Фамилия друга 1",
    title: "Гарри Поттер",
  },
  {
    _id: "64060df7885aa09e184268de",
    author: "Ф. Фитцджеральд",
    deadline: "",
    friendsbook: false,
    name: "",
    notes: ["Заметка к книге Великий Гэтсби"],
    patronymic: "",
    surname: "",
    title: "Великий Гэтсби",
  },
  {
    _id: "64060df9885aa09e184268df",
    author: "Р. Кийосаки",
    deadline: "",
    friendsbook: false,
    name: "",
    notes: ["Заметка к книге Богатый папа, бедный папа"],
    patronymic: "",
    surname: "",
    title: "Богатый папа, бедный папа",
  },
  {
    _id: "64060dfa885aa09e184268e0",
    author: "вцфвфы",
    deadline: "",
    friendsbook: false,
    name: "",
    patronymic: "",
    surname: "",
    title: "вцфвыф",
  },
  {
    _id: "64060dfa885aa09e184268e0",
    author: "Author",
    deadline: "",
    friendsbook: false,
    name: "",
    patronymic: "",
    surname: "",
    title: "my book",
  },
];
